#!/bin/bash
if [ $# -lt 3]; then
    echo "El comando esta mal escrito. El modo correcto es mifind <camino> -opciones"
    exit -1
fi

if [ $#%2 -eq 0]; then	
    directorio = $1
else
    directorio = CurrDir
fi

while  read i 
do

    if [ -d $directorio/$i]
    then
        directorio=$directorio/$i
        profundidad++
    fi

done < $(ls $directorio) 



exit 
echo ¨no se ha encontrado nada¨
exit 0